# create a list of places, not in alpha order
places = ['assen','motegi','mugello','brno','le mans','catalunya','valencia','jerez','sachsenring','aragon']

print("List of race tracks..")
print(places)
print("\nLet's display in alphabetical order...")
print(sorted(places))
print("\nWe didn't change the original list...")
print(places)
print("\nOkay, now for reverse alphabetical order...")
print(sorted(places, reverse=True))
print("\nWe still kept the original list...")
print(places)
print("\nThis time we will change the order of the original list.")
print("The original list...")
print(places)
print("And the new order of the list...")
places.reverse()
print(places)
print("\nAnd if we reverse again, we are back to the original order.")
places.reverse()
print(places)
print("\nLet's change the list to store it in alphabetical order...")
places.sort()
print(places)
print("\nReverse alpha? Why not...")
places.sort(reverse=True)
print(places)
print("\nHow long is this list anyway?")
print(f"The length of this list of tracks is: {len(places)}")
